feat: code signing

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -71,6 +71,39 @@ jobs:
       run: |
         dotnet publish src/Everywhere.Windows/Everywhere.Windows.csproj -c Release --self-contained true -p:AssemblyVersion=$env:VERSION -p:FileVersion=$env:VERSION -o ./publish --no-restore
 
+    - name: Install SimplySignDesktop
+      shell: pwsh
+      run: |
+        $msiPath = "tools/sign_windows/SimplySignDesktop-9.3.3.71-64-bit-en.msi"
+        $logPath = "install.log"
+        Write-Host "Installing SimplySignDesktop..."
+        $process = Start-Process msiexec -ArgumentList "/i `"$msiPath`" /passive /norestart /l*v `"$logPath`"" -Wait -PassThru
+        
+        if ($process.ExitCode -ne 0) {
+            Write-Error "SimplySignDesktop installation failed with exit code $($process.ExitCode)"
+            if (Test-Path $logPath) {
+                Write-Host "Install Log Content:"
+                Get-Content $logPath
+            }
+            exit $process.ExitCode
+        }
+        Write-Host "SimplySignDesktop installed successfully."
+
+    - name: Set up Python
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.10'
+
+    - name: Login and Sign
+      shell: pwsh
+      env:
+          SIGN_USERNAME: ${{ secrets.SIGN_USERNAME }}
+          SIGN_OTP_TOKEN: ${{ secrets.SIGN_OTP_TOKEN }}
+      run: |
+        python -m pip install --upgrade pip
+        pip install pyotp
+        python -u tools/sign_windows/sign.py ./publish
+
     - name: Install Inno Setup
       shell: pwsh
       run: |
